CLASSES=\
	org.snmp4j.AbstractTarget	\
	org.snmp4j.asn1.BER	\
	org.snmp4j.asn1.BERInputStream	\
	org.snmp4j.asn1.BEROutputStream	\
	org.snmp4j.asn1.BERSerializable	\
	org.snmp4j.CertifiedIdentity	\
	org.snmp4j.CertifiedTarget	\
	org.snmp4j.CommandResponder	\
	org.snmp4j.CommandResponderEvent	\
	org.snmp4j.CommunityTarget	\
	org.snmp4j.DefaultTimeoutModel	\
	org.snmp4j.event.AuthenticationFailureEvent	\
	org.snmp4j.event.AuthenticationFailureListener	\
	org.snmp4j.event.CounterEvent	\
	org.snmp4j.event.CounterListener	\
	org.snmp4j.event.ResponseEvent	\
	org.snmp4j.event.ResponseListener	\
	org.snmp4j.event.SnmpEngineEvent	\
	org.snmp4j.event.SnmpEngineListener	\
	org.snmp4j.event.UsmUserEvent	\
	org.snmp4j.event.UsmUserListener	\
	org.snmp4j.log.ConsoleLogAdapter	\
	org.snmp4j.log.ConsoleLogFactory	\
	org.snmp4j.log.LogAdapter	\
	org.snmp4j.log.LogFactory	\
	org.snmp4j.log.LogLevel	\
	org.snmp4j.log.LogProxy	\
	org.snmp4j.log.NoLogger	\
	org.snmp4j.log.Slf4jLogAdapter	\
	org.snmp4j.log.Slf4jLogFactory	\
	org.snmp4j.MessageDispatcher	\
	org.snmp4j.MessageDispatcherImpl	\
	org.snmp4j.MessageException	\
	org.snmp4j.mp.CounterSupport	\
	org.snmp4j.mp.DefaultCounterListener	\
	org.snmp4j.mp.EngineIdCacheSize	\
	org.snmp4j.mp.MessageID	\
	org.snmp4j.mp.MessageProcessingModel	\
	org.snmp4j.mp.MPv1	\
	org.snmp4j.mp.MPv2c	\
	org.snmp4j.mp.MPv3	\
	org.snmp4j.mp.MutableStateReference	\
	org.snmp4j.mp.PduHandle	\
	org.snmp4j.mp.PduHandleCallback	\
	org.snmp4j.mp.RequestStatistics	\
	org.snmp4j.mp.SimpleMessageID	\
	org.snmp4j.mp.SnmpConstants	\
	org.snmp4j.mp.StateReference	\
	org.snmp4j.mp.StatusInformation	\
	org.snmp4j.mp.TimedMessageID	\
	org.snmp4j.MutablePDU	\
	org.snmp4j.PDU	\
	org.snmp4j.PDUv1	\
	org.snmp4j.ScopedPDU	\
	org.snmp4j.SecureTarget	\
	org.snmp4j.security.AuthenticationProtocol	\
	org.snmp4j.security.AuthGeneric	\
	org.snmp4j.security.AuthHMAC128SHA224	\
	org.snmp4j.security.AuthHMAC192SHA256	\
	org.snmp4j.security.AuthHMAC256SHA384	\
	org.snmp4j.security.AuthHMAC384SHA512	\
	org.snmp4j.security.AuthMD5	\
	org.snmp4j.security.AuthSHA	\
	org.snmp4j.security.AuthSHA2	\
	org.snmp4j.security.ByteArrayWindow	\
	org.snmp4j.security.CipherPool	\
	org.snmp4j.security.DecryptParams	\
	org.snmp4j.security.nonstandard.NonStandardSecurityProtocol	\
	org.snmp4j.security.nonstandard.PrivAES192With3DESKeyExtension	\
	org.snmp4j.security.nonstandard.PrivAES256With3DESKeyExtension	\
	org.snmp4j.security.nonstandard.PrivAESWith3DESKeyExtension	\
	org.snmp4j.security.Priv3DES	\
	org.snmp4j.security.PrivacyGeneric	\
	org.snmp4j.security.PrivacyProtocol	\
	org.snmp4j.security.PrivAES	\
	org.snmp4j.security.PrivAES128	\
	org.snmp4j.security.PrivAES192	\
	org.snmp4j.security.PrivAES256	\
	org.snmp4j.security.PrivDES	\
	org.snmp4j.security.Salt	\
	org.snmp4j.security.SecurityLevel	\
	org.snmp4j.security.SecurityModel	\
	org.snmp4j.security.SecurityModels	\
	org.snmp4j.security.SecurityParameters	\
	org.snmp4j.security.SecurityProtocol	\
	org.snmp4j.security.SecurityProtocols	\
	org.snmp4j.security.SecurityStateReference	\
	org.snmp4j.security.SNMPv3SecurityModel	\
	org.snmp4j.security.TSM	\
	org.snmp4j.security.TsmSecurityParameters	\
	org.snmp4j.security.TsmSecurityStateReference	\
	org.snmp4j.security.USM	\
	org.snmp4j.security.UsmSecurityParameters	\
	org.snmp4j.security.UsmSecurityStateReference	\
	org.snmp4j.security.UsmTimeEntry	\
	org.snmp4j.security.UsmTimeTable	\
	org.snmp4j.security.UsmUser	\
	org.snmp4j.security.UsmUserEntry	\
	org.snmp4j.security.UsmUserTable	\
	org.snmp4j.Session	\
	org.snmp4j.smi.AbstractVariable	\
	org.snmp4j.smi.Address	\
	org.snmp4j.smi.AssignableFromByteArray	\
	org.snmp4j.smi.AssignableFromIntArray	\
	org.snmp4j.smi.AssignableFromInteger	\
	org.snmp4j.smi.AssignableFromLong	\
	org.snmp4j.smi.AssignableFromString	\
	org.snmp4j.smi.BitString	\
	org.snmp4j.smi.Counter32	\
	org.snmp4j.smi.Counter64	\
	org.snmp4j.smi.Gauge32	\
	org.snmp4j.smi.GenericAddress	\
	org.snmp4j.smi.Integer32	\
	org.snmp4j.smi.IpAddress	\
	org.snmp4j.smi.MaxAccess	\
	org.snmp4j.smi.Null	\
	org.snmp4j.smi.OctetString	\
	org.snmp4j.smi.OID	\
	org.snmp4j.smi.Opaque	\
	org.snmp4j.smi.ReadonlyVariableCallback	\
	org.snmp4j.smi.SMIAddress	\
	org.snmp4j.smi.SMIConstants	\
	org.snmp4j.smi.SshAddress	\
	org.snmp4j.smi.SubIndexInfo	\
	org.snmp4j.smi.SubIndexInfoImpl	\
	org.snmp4j.smi.TcpAddress	\
	org.snmp4j.smi.TimeTicks	\
	org.snmp4j.smi.TlsAddress	\
	org.snmp4j.smi.TransportIpAddress	\
	org.snmp4j.smi.UdpAddress	\
	org.snmp4j.smi.UnsignedInteger32	\
	org.snmp4j.smi.Variable	\
	org.snmp4j.smi.VariableBinding	\
	org.snmp4j.smi.VariantVariable	\
	org.snmp4j.smi.VariantVariableCallback	\
	org.snmp4j.Snmp	\
	org.snmp4j.SNMP4JSettings	\
	org.snmp4j.Target	\
	org.snmp4j.test.MultiThreadedTrapReceiver	\
	org.snmp4j.TimeoutModel	\
	org.snmp4j.tools.console.LogControl	\
	org.snmp4j.tools.console.SnmpRequest	\
	org.snmp4j.transport.AbstractTransportMapping	\
	org.snmp4j.transport.ConnectionOrientedTransportMapping	\
	org.snmp4j.transport.DefaultSshTransportMapping	\
	org.snmp4j.transport.DefaultTcpTransportMapping	\
	org.snmp4j.transport.DefaultUdpTransportMapping	\
	org.snmp4j.transport.DummyTransport	\
	org.snmp4j.transport.MessageLength	\
	org.snmp4j.transport.MessageLengthDecoder	\
	org.snmp4j.transport.ssh.SshSession	\
	org.snmp4j.transport.ssh.SshTransportAdapter	\
	org.snmp4j.transport.TcpTransportMapping	\
	org.snmp4j.transport.tls.DefaultTlsTmSecurityCallback	\
	org.snmp4j.transport.tls.PropertiesTlsTmSecurityCallback	\
	org.snmp4j.transport.tls.SecurityNameMapping	\
	org.snmp4j.transport.tls.TlsTmSecurityCallback	\
	org.snmp4j.transport.TLSTM	\
	org.snmp4j.transport.TransportListener	\
	org.snmp4j.transport.TransportMappings	\
	org.snmp4j.transport.TransportStateEvent	\
	org.snmp4j.transport.TransportStateListener	\
	org.snmp4j.transport.UdpTransportMapping	\
	org.snmp4j.transport.UnsupportedAddressClassException	\
	org.snmp4j.TransportMapping	\
	org.snmp4j.TransportStateReference	\
	org.snmp4j.uri.SnmpURI	\
	org.snmp4j.uri.SnmpUriCallback	\
	org.snmp4j.uri.SnmpUriResponse	\
	org.snmp4j.User	\
	org.snmp4j.UserTarget	\
	org.snmp4j.util.AbstractSnmpUtility	\
	org.snmp4j.util.ArgumentParser	\
	org.snmp4j.util.CommonTimer	\
	org.snmp4j.util.DefaultPDUFactory	\
	org.snmp4j.util.DefaultThreadFactory	\
	org.snmp4j.util.DefaultTimerFactory	\
	org.snmp4j.util.EnumerationIterator	\
	org.snmp4j.util.MultiThreadedMessageDispatcher	\
	org.snmp4j.util.OIDTextFormat	\
	org.snmp4j.util.PDUFactory	\
	org.snmp4j.util.RetrievalEvent	\
	org.snmp4j.util.SchedulerTask	\
	org.snmp4j.util.SimpleOIDTextFormat	\
	org.snmp4j.util.SimpleVariableTextFormat	\
	org.snmp4j.util.SnmpConfigurator	\
	org.snmp4j.util.TableEvent	\
	org.snmp4j.util.TableListener	\
	org.snmp4j.util.TableUtils	\
	org.snmp4j.util.TaskScheduler	\
	org.snmp4j.util.ThreadFactory	\
	org.snmp4j.util.ThreadPool	\
	org.snmp4j.util.TimerFactory	\
	org.snmp4j.util.TreeEvent	\
	org.snmp4j.util.TreeListener	\
	org.snmp4j.util.TreeUtils	\
	org.snmp4j.util.VariableTextFormat	\
	org.snmp4j.util.WorkerPool	\
	org.snmp4j.util.WorkerTask	\
	org.snmp4j.version.VersionInfo
